### ISSUE TITLE
画像の保存方法を変更した方が良いかもな件

### ISSUE THREAD

**Issue by 2101002ishikawa** [shooooooogo/2023Dev3Early#28]
現在は画像データをそのままデータベースにぶち込み遊ばしていますが、
画像をサーバ上に保存して、パスをデータベースに保存する方法に変えるのもありかもしれません。
現在、sqlのみで画像をデータベースに保存する方法を探しているのですが、load_file()メソッドを利用するには少々設定を変える必要がありそうで、sqlのみで実装を行う場合には仕様変更した方が良い可能性があります。
しかし、開発がある程度進んでいることもあり、画像を取り扱っているページも増えており、影響範囲がある程度広いと思われるので、話し合ったうえで検討を加速させようと思います。

**Comment by shooooooogo** [comment]
リーダーがなんとかしときます

**Comment by shooooooogo** [comment]
リーダーが指示を出しておきました

**Comment by shooooooogo** [comment]
ありがとうございます
