### ISSUE TITLE
サーバ上に画像を保存することで、imgフォルダの使い方を話し合った方がいいおじさん

### ISSUE THREAD

**Issue by 2101002ishikawa** [shooooooogo/2023Dev3Early#29]
現在、下書き作成画面をコーディングしているのですが、画像をサーバ上に保存する際に、フォルダを分けて画像を保存するようにコーディングしています。
しかし、現在画像を用途ごと(例:アイコン、サムネイル)にフォルダを分けるか、ユーザごとにフォルダを分けるかで迷っています。
今のところは用途ごとでいい感じですが、運用まで考えるとユーザごともワンチャンあるかもと思い付きで書き込みました。
リーダー解決お願いします。

**Comment by 2101002ishikawa** [comment]
chatGPT君に聞いてきました。
画像をサーバ上に保存する方法には、様々な考慮事項があります。どちらの方法が運用や保守に優れているかは、具体的な要件やシステムの設計に依存します。ただし、一般的な考え方を以下に示します。

画像を用途別作成されたフォルダに格納する方法

メリット:
フォルダ構造が整理され、用途ごとに画像が分類されるため、管理が容易になります。
同じ用途の画像が複数のユーザによって共有される場合、1つのフォルダに格納することで重複を避けられます。
デメリット:
ユーザごとに画像のパスや権限を管理する必要があります。
ユーザごとのフォルダ数が増えるため、フォルダの数が増えすぎる可能性があり、パフォーマンスや可読性に影響を与える場合があります。
画像をユーザごとに作成されたフォルダに格納する方法

メリット:
各ユーザごとに独立したフォルダに画像が格納されるため、管理やアクセス権の管理が容易になります。
フォルダの数がユーザの数に比例するため、フォルダの数が増えても管理しやすいです。
デメリット:
同じ用途の画像が複数のユーザによって共有される場合、重複して保存される可能性があります。
ユーザごとのフォルダが増えるため、フォルダ構造が複雑化し、管理がやや複雑になる場合があります。
どちらの方法が優れているかは、具体的な要件やシステムの特性により異なります。例えば、画像の重複を避ける必要があるか、ユーザごとのデータの独立性が必要か、管理のしやすさが重要かなど、様々な要素を考慮する必要があります。システムの要件や目標に基づいて、どの方法が最適かを判断してください。

**Comment by shooooooogo** [comment]
If you think you can manage permissions for each user, you can separate folders for each user.

**Comment by shooooooogo** [comment]
ユーザーごとの権限の管理ができそうやったら、ユーザーごとにフォルダを分けてもいいと思います。
